### ISSUE TITLE
How to treat "NA", "TR", and "<.0.00???"

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#101] opened 2016-04-19 19:06 UTC
The treatment of the "NA", "TR", and "<.0.00???" in the database has been brought up.  For the actual database, I am suggesting we use a numeric code, e.g. 999 to represent all of the "NA"s and another numeric code e.g. 888 to represent all of the "TR"s.  In addition, we will define all of the small values reported as ",0.00??" as "TR", with the actual reported values in the notes.  In addition, if the paper defines "TR" we will put that in the notes as well.  If the "TR" is not define, we will so state in the notes. We will just need to select numeric codes that cannot be confused with real data, and we will need to have this explicitly stated with the download.  I would suggest for the query output, since those are not downloadable, that we use the "NA" and "TR" in the output for the suggested new details page.

**Comment by jhpoelen** [comment] 2016-04-22 19:55
duplicate of  https://github.com/GoMexSI/interaction-data/issues/8

**Comment by jsimons9** [comment] 2016-05-26 15:22
Since this is a duplicate, can we close or delete it??

**Comment by jhpoelen** [comment] 2016-05-26 16:42
Sounds like a plan. Let me know if you need any help closing the issue.

**Comment by jsimons9** [comment] 2016-05-27 14:59
Well I am looking at the issues page and do not see anything very obvious as far as closing an issue – perhaps you can enlighten me!!

Jim

**Comment by tmitchell1** [comment] 2016-07-27 15:51
Please see the issue entitled "File changes." You can find this in the issues under the interaction data.

**Closed by tmitchell1** 2016-07-27 15:51 UTC
