### ISSUE TITLE
Show centroids of studies on spatial query map

### ISSUE THREAD

**Issue by jsimons9** [GoMexSI/gomexsi-web#85] opened 2013-11-13 22:25 UTC
Now that we have 49 different sources of data it would be a good idea to have the centroids of these studies show up on the spatial query map so that someone does not do a query in a location with no data.

**Comment by reedhewitt** [comment] 2016-01-20 15:53
I'm now working on the front-end part of this.  Jorrit, is there a way to get all the data points from the Globi API (and maybe also get data points limited by taxonomy)?

As far as the user interface goes, I think it would be effective to cluster the points together depending on the zoom level of the map.  The more zoomed out the map is, the more points will be grouped together.  As you zoom in to a specific area, you will be able to see the individual points at a more granular level. (See https://github.com/googlemaps/js-marker-clusterer for example.)

**Comment by reedhewitt** [comment] 2016-01-29 22:18
In my local development environment I have the spatial query page updated to show centroids.  I need to get with Jorrit and see about retrieving all the centroids for GoMexSI data only.  Right now, I'm using the GloBI API to get all locations (using http://api.globalbioticinteractions.org/locations) and then filtering them down with a crude polygon of the gulf.

The initial page view shows all centroids as small red dots.  After a search is made, the dots inside the search area turn green if they contained results or gray if they did not.  (I experimented with clustering the dots, but that gets in the way of color coding, so I decided against it.)

A screenshot is attached.  Jim, is this the kind of look you were hoping for?

<img width="1054" alt="spatial query map" src="https://cloud.githubusercontent.com/assets/957141/12689644/d1379f74-c6a3-11e5-9cdd-28f6b8659644.png">

**Comment by jhpoelen** [comment] 2016-01-30 01:04
@reedhewitt looks pretty cool to me! Curious what Jim has to say about it.

**Comment by jsimons9** [comment] 2016-02-01 17:10
Yes, I like the way that is looking – much more informative as to where data are located.  I assume that is GloBI thus some of the points are probably not GoMexSI points.

jim

**Comment by reedhewitt** [comment] 2016-02-08 23:15
@jhpoelen - is there a way to get the data from http://api.globalbioticinteractions.org/locations but limited to only GoMexSI?

**Comment by jhpoelen** [comment] 2016-02-09 18:18
@reedhewitt not yet, but happy to add the functionality . . . how about something like http://api.globalbioticinteractions.org/locations?accordingTo=gomexsi ?

**Comment by jhpoelen** [comment] 2016-02-09 19:19
@reedhewitt by the way, if you don't mind repeating locations, you can use the existing api to requests lat/lng information using http://api.globalbioticinteractions.org/interaction?accordingTo=gomexsi&includeObservations=true&field=latitude&field=longitude&limit=10&offset=5 . Please let me know your preference.

**Comment by reedhewitt** [comment] 2016-02-09 22:14
@jhpoelen That will work great.  What's the difference between those two links?  The second one is much shorter even when I remove the limit and offset parameters.

**Comment by jhpoelen** [comment] 2016-02-09 22:17
the first link returns distinct locations, the second one returns the locations associated with individual interaction records. So, the former contains only unique lat/lng/depth combinations, and the latter may contain duplicates. Please do note that you'd have to page through the result for the second one, because the results are limited to 1024 results by default. This said, which method do you prefer?

**Comment by reedhewitt** [comment] 2016-02-09 23:04
I think the first one would generally be better — no duplicates to resolve and no paging.  Would the individual interaction records be equivalent to the lat/lng of the search results (the point you see when you go to a result and click on the "Map" link to view the centroid)?

**Comment by jhpoelen** [comment] 2016-02-09 23:11
Ok. thanks for sharing your preference. I'll proceed to implement the http://api.globalbioticinteractions.org/locations?accordingTo=gomexsi . And yes, the second method are simply a list of interactions where only the lat/lng params are retrieved. Will update this issue if the method is available. Thanks!

**Comment by jhpoelen** [comment] 2016-02-10 02:07
@reedhewitt I've implemented the requested functionality: http://api.globalbioticinteractions.org/locations?accordingTo=gomexsi now returns only locations reported by GoMexSI. Please confirm by closing this issue.

**Comment by reedhewitt** [comment] 2016-02-10 02:20
@jhpoelen Looks good to me!

**Closed by reedhewitt** 2016-02-10 02:20 UTC
Labels: enhancement

**Comment by reedhewitt** [comment] 2016-02-10 02:31
I'm seeing a lot of points that are not anywhere near the Gulf of Mexico.  Is this expected behavior?  If so, should I do something to filter out points that are not in the Gulf?  (Previously, when I was using all GloBI locations, I set up a rough polygon of the gulf and filtered against that.  Seemed to work fine from a technical standpoint, but I don't think my boundary should have the final say on what is in or not in the search results.)

<img width="672" alt="screen shot 2016-02-09 at 8 26 29 pm" src="https://cloud.githubusercontent.com/assets/957141/12937164/7d410ed4-cf6b-11e5-84cf-03f3157b0fd4.png">

**Comment by jhpoelen** [comment] 2016-02-10 02:40
@reedhewitt thanks for spotting this. It turned out to be a caching issue and it should be resolved now. Please confirm that now only locations in Gulf of Mexico are present.

**Comment by reedhewitt** [comment] 2016-02-10 13:27
@jhpoelen Much improved!  There are a handful of points along the east coast and one in Illinois, plus one in central Asia.  I'm guessing those probably don't matter and won't affect the usability of the spatial query.  Just thought it was interesting.  When the map loads, it is zoomed in to the Gulf of Mexico, so people probably won't even notice if there are a few random points in other areas.

<img width="683" alt="screen shot 2016-02-10 at 7 23 46 am" src="https://cloud.githubusercontent.com/assets/957141/12948418/b3cac132-cfc7-11e5-8f03-ffb606229bd6.png">

<img width="690" alt="screen shot 2016-02-10 at 7 23 18 am" src="https://cloud.githubusercontent.com/assets/957141/12948420/b65fba38-cfc7-11e5-950d-1f44beff6e62.png">

**Comment by jhpoelen** [comment] 2016-02-10 16:13
@reedhewitt  thanks for sharing this information! More likely than not, these locations are data errors. Could you please create a separate bugs for this so that we can have a look at this? Details matter!

**Comment by jsimons9** [comment] 2016-02-10 16:24
Good point.  Better to find out if they are bugs or mis-plotted points.

Jim
